<?php

namespace App\Modules\Project\Database\Seeders;

use App\Modules\Project\Domain\Entities\Project;

use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        Project::truncate();

        $projects = [
            [
                'title' => 'Laravel CMS Portfolio',
                'slug' => Str::slug('Laravel CMS Portfolio'),
                'description' => 'A personal portfolio CMS built with Laravel 10 using Clean Architecture and Modular structure.',
                'technologies' => json_encode(['Laravel', 'PHP', 'MySQL', 'REST API']),
                'url' => 'https://portfolio.example.com',
                'github_url' => 'https://github.com/your-username/laravel-cms-portfolio',
                'image' => 'projects/laravel-cms.png',
                'status' => 'published',
                'start_date' => '2024-01-10',
                'end_date' => '2024-02-05',
                'completed_at' => '2024-02-05',
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'title' => 'BabyShop API Backend',
                'slug' => Str::slug('BabyShop API Backend'),
                'description' => 'An e-commerce backend for baby clothes using Go (Golang), GORM, MySQL and Clean Architecture.',
                'technologies' => json_encode(['Golang', 'GORM', 'MySQL', 'Docker', 'JWT']),
                'url' => 'https://api.babyshop.com',
                'github_url' => 'https://github.com/your-username/babyshop-api',
                'image' => 'projects/babyshop-api.png',
                'status' => 'published',
                'start_date' => '2024-03-01',
                'end_date' => '2024-04-01',
                'completed_at' => '2024-04-01',
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'title' => 'React CMS Frontend',
                'slug' => Str::slug('React CMS Frontend'),
                'description' => 'Frontend of CMS portfolio using ReactJS and Next.js, connecting to Laravel API via JWT.',
                'technologies' => json_encode(['React', 'Next.js', 'Tailwind CSS', 'JWT']),
                'url' => 'https://cms-frontend.example.com',
                'github_url' => 'https://github.com/your-username/cms-frontend',
                'image' => 'projects/react-cms.png',
                'status' => 'published',
                'start_date' => '2024-02-20',
                'end_date' => '2024-03-15',
                'completed_at' => '2024-03-15',
                'is_featured' => false,
                'order' => 3,
            ],
            [
                'title' => 'Resume PDF Generator',
                'slug' => Str::slug('Resume PDF Generator'),
                'description' => 'A web app to design and export professional CVs using MathJax and Puppeteer.',
                'technologies' => json_encode(['Node.js', 'Puppeteer', 'MathJax', 'Laravel']),
                'url' => 'https://cv.example.com',
                'github_url' => 'https://github.com/your-username/cv-generator',
                'image' => 'projects/cv-generator.png',
                'status' => 'draft',
                'start_date' => '2024-06-01',
                'end_date' => null,
                'completed_at' => null,
                'is_featured' => false,
                'order' => 4,
            ],
            [
                'title' => 'Vue Ecommerce Dashboard',
                'slug' => Str::slug('Vue Ecommerce Dashboard'),
                'description' => 'A modern admin dashboard for e-commerce built with Vue 3 and Tailwind CSS.',
                'technologies' => json_encode(['Vue 3', 'Tailwind CSS', 'Pinia', 'Axios']),
                'url' => 'https://dashboard.example.com',
                'github_url' => 'https://github.com/your-username/vue-ecommerce-dashboard',
                'image' => 'projects/vue-dashboard.png',
                'status' => 'published',
                'start_date' => '2023-11-01',
                'end_date' => '2023-12-01',
                'completed_at' => '2023-12-01',
                'is_featured' => false,
                'order' => 5,
            ],
            [
                'title' => 'Golang Blog API',
                'slug' => Str::slug('Golang Blog API'),
                'description' => 'A clean architecture blog API written in Golang using Gin and GORM.',
                'technologies' => json_encode(['Go', 'Gin', 'GORM', 'MySQL']),
                'url' => 'https://api.blog.example.com',
                'github_url' => 'https://github.com/your-username/go-blog-api',
                'image' => 'projects/go-blog-api.png',
                'status' => 'published',
                'start_date' => '2024-05-10',
                'end_date' => '2024-05-30',
                'completed_at' => '2024-05-30',
                'is_featured' => false,
                'order' => 6,
            ],
            [
                'title' => 'Tailwind Landing Page',
                'slug' => Str::slug('Tailwind Landing Page'),
                'description' => 'A responsive and animated landing page template built with Tailwind CSS.',
                'technologies' => json_encode(['HTML', 'Tailwind CSS', 'Alpine.js']),
                'url' => 'https://landing.example.com',
                'github_url' => 'https://github.com/your-username/tailwind-landing-page',
                'image' => 'projects/tailwind-landing.png',
                'status' => 'published',
                'start_date' => '2024-01-05',
                'end_date' => '2024-01-07',
                'completed_at' => '2024-01-07',
                'is_featured' => false,
                'order' => 7,
            ],
            [
                'title' => 'Laravel Multi Auth System',
                'slug' => Str::slug('Laravel Multi Auth System'),
                'description' => 'A Laravel 10 project implementing multi-role authentication system.',
                'technologies' => json_encode(['Laravel', 'PHP', 'Spatie Roles', 'JWT']),
                'url' => null,
                'github_url' => 'https://github.com/your-username/laravel-multi-auth',
                'image' => 'projects/laravel-multiauth.png',
                'status' => 'published',
                'start_date' => '2024-02-01',
                'end_date' => '2024-02-20',
                'completed_at' => '2024-02-20',
                'is_featured' => false,
                'order' => 8,
            ],
            [
                'title' => 'AWS EC2 Deployment Tool',
                'slug' => Str::slug('AWS EC2 Deployment Tool'),
                'description' => 'A shell script and Laravel app to automate Laravel deployment to AWS EC2.',
                'technologies' => json_encode(['AWS EC2', 'Shell Script', 'Laravel', 'Nginx']),
                'url' => null,
                'github_url' => 'https://github.com/your-username/aws-ec2-deploy',
                'image' => 'projects/aws-deploy.png',
                'status' => 'draft',
                'start_date' => '2024-06-01',
                'end_date' => null,
                'completed_at' => null,
                'is_featured' => false,
                'order' => 9,
            ],
            [
                'title' => 'Portfolio with Animations',
                'slug' => Str::slug('Portfolio with Animations'),
                'description' => 'A portfolio website built with GSAP animations and Next.js.',
                'technologies' => json_encode(['Next.js', 'GSAP', 'Framer Motion']),
                'url' => 'https://animated-portfolio.example.com',
                'github_url' => 'https://github.com/your-username/animated-portfolio',
                'image' => 'projects/animated-portfolio.png',
                'status' => 'published',
                'start_date' => '2024-03-15',
                'end_date' => '2024-04-10',
                'completed_at' => '2024-04-10',
                'is_featured' => true,
                'order' => 10,
            ],
            [
                'title' => 'React Admin CMS',
                'slug' => Str::slug('React Admin CMS'),
                'description' => 'A modular admin CMS system with authentication and protected routes.',
                'technologies' => json_encode(['React', 'Next.js', 'JWT', 'Tailwind CSS']),
                'url' => 'https://admin.cms.example.com',
                'github_url' => 'https://github.com/your-username/react-admin-cms',
                'image' => 'projects/react-admin.png',
                'status' => 'published',
                'start_date' => '2024-03-20',
                'end_date' => '2024-04-15',
                'completed_at' => '2024-04-15',
                'is_featured' => false,
                'order' => 11,
            ],
            [
                'title' => 'Blog Import/Export Plugin',
                'slug' => Str::slug('Blog Import/Export Plugin'),
                'description' => 'A WordPress plugin to import and export blog posts with JSON and Excel.',
                'technologies' => json_encode(['PHP', 'WordPress', 'Excel', 'JSON']),
                'url' => null,
                'github_url' => 'https://github.com/your-username/wp-blog-import-export',
                'image' => 'projects/wp-plugin.png',
                'status' => 'published',
                'start_date' => '2024-05-01',
                'end_date' => '2024-05-10',
                'completed_at' => '2024-05-10',
                'is_featured' => false,
                'order' => 12,
            ],
            [
                'title' => 'Docker Laravel Starter Kit',
                'slug' => Str::slug('Docker Laravel Starter Kit'),
                'description' => 'A Dockerized Laravel starter project for rapid development.',
                'technologies' => json_encode(['Laravel', 'Docker', 'MySQL', 'Redis']),
                'url' => null,
                'github_url' => 'https://github.com/your-username/docker-laravel-starter',
                'image' => 'projects/docker-laravel.png',
                'status' => 'published',
                'start_date' => '2024-04-01',
                'end_date' => '2024-04-05',
                'completed_at' => '2024-04-05',
                'is_featured' => false,
                'order' => 13,
            ],
            [
                'title' => 'Resume Builder App',
                'slug' => Str::slug('Resume Builder App'),
                'description' => 'A modern app for building resumes with PDF export, responsive design.',
                'technologies' => json_encode(['Laravel', 'Inertia.js', 'Vue 3', 'Tailwind CSS']),
                'url' => 'https://resumebuilder.example.com',
                'github_url' => 'https://github.com/your-username/resume-builder',
                'image' => 'projects/resume-builder.png',
                'status' => 'published',
                'start_date' => '2024-06-15',
                'end_date' => '2024-07-01',
                'completed_at' => '2024-07-01',
                'is_featured' => false,
                'order' => 14,
            ],

        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
